export const FETCH_AMAZING_PEOPLE_REQUEST = 'FETCH_AMAZING_PEOPLE_REQUEST';
export const FETCH_AMAZING_PEOPLE_SUCCESS = 'FETCH_AMAZING_PEOPLE_SUCCESS';
export const FETCH_AMAZING_PEOPLE_ERROR = 'FETCH_AMAZING_PEOPLE_ERROR';
